
2024-06-12 07:39:06,888 chess.engine (engine.py:1062) DEBUG <UciProtocol (pid=161026)>: << position startpos moves c2c4 g8f6 b1c3 e7e6 d1a4 c7c5 g1f3 f8e7 e2e4 b8c6 f1d3 c6b4 d3e2 b4c6 e1g1 e8g8 e4e5 f6g4 c3b5 d8b6 e2d3 c6b4 d3e4 d7d5 e5d6 e7f6 h2h3 g4h6 a2a3 b4a6 d2d4 c5d4 c1h6 g7h6 a4c2 d4d3 e4d3 g8g7 a1d1 c8d7 d3e2 b6c6 e2d3 a6c5 b2b4 c5d3 c2d3 a7a6 f3d4 c6b6 d3g3 g7h8 g3f4 f6d4 b5d4 f7f6 c4c5 b6a7 f4h6 e6e5 d4f3 e5e4 f3h4 h8g8 f1e1 d7a4 d1d2 a8e8 d2d4 a4d7 d4e4 e8e4 e1e4 f8f7 e4f4 f7f8 f4f6 f8f6 h6f6 a7b8 f6g5 g8f7 g5e7 f7g8 e7d7 g8h8 d7e7 b8c8 d6d7 c8b8 d7d8q b8d8 e7d8 h8g7 d8d7 g7g8 h4f5 g8f8 f5h6
2024-06-12 07:39:06,888 chess.engine (engine.py:1062) DEBUG <UciProtocol (pid=161026)>: << go wtime 44400 btime 77060 winc 3000 binc 3000
2024-06-12 07:39:06,922 chess.engine (engine.py:1088) DEBUG <UciProtocol (pid=161026)>: >> info depth 2 time 30 nodes 667
2024-06-12 07:39:06,922 chess.engine (engine.py:1088) DEBUG <UciProtocol (pid=161026)>: >> bestmove d5d4
2024-06-12 07:39:06,923 lib.engine_wrapper (engine_wrapper.py:185) ERROR Ending game due to bot attempting an illegal move.

2024-06-12 11:33:19,854 chess.engine (engine.py:1062) DEBUG <UciProtocol (pid=165389)>: << position startpos moves c2c4 e7e5 b1c3 g8f6 g1f3 b8c6 e2e4 f8b4 f1d3 d7d6 a2a3 b4c5 b2b4 c5b6 h2h3 c8e6 d1a4 e8e7 c1b2 a7a6 a1d1 d8d7 c3d5 f6d5 c4d5 c6d4 a4d7 e6d7 f3d4 b6d4 b2d4 e5d4 d1c1 e7d8 c1c4 d7b5 c4d4 c7c5 d5c6 b5d3 d4d3 d8c7 c6b7 a8e8 e1g1 e8e4 d3f3 f7f6 f3g3 g7g5 g3e3 e4e3 f2e3 h8f8 f1f5 c7b7 f5d5 f8e8 d5d6 b7b8 d6f6 e8d8 d2d4 d8e8 g1f2 g5g4 h3g4 a6a5 b4a5 b8a8 a5a6 a8a7 a3a4 e8e7 a4a5 e7e8 f6c6 e8e7 f2f3 e7e8 e3e4 e8e7 e4e5 e7d7 f3e4 d7e7 e5e6 h7h6 e4f5 e7g7 f5f4 g7e7 c6d6 e7g7 d6d7 g7d7 e6d7 a7a6 d7d8q a6b5 f4f5
2024-06-12 11:33:19,855 chess.engine (engine.py:1062) DEBUG <UciProtocol (pid=165389)>: << go wtime 46280 btime 122179 winc 3000 binc 3000
2024-06-12 11:33:19,929 chess.engine (engine.py:1088) DEBUG <UciProtocol (pid=165389)>: >> info depth 3 time 69 nodes 1648
2024-06-12 11:33:19,929 chess.engine (engine.py:1088) DEBUG <UciProtocol (pid=165389)>: >> bestmove c5d4
2024-06-12 11:33:19,930 lib.engine_wrapper (engine_wrapper.py:185) ERROR Ending game due to bot attempting an illegal move.

2024-06-12 11:46:15,814 chess.engine (engine.py:1062) DEBUG <UciProtocol (pid=165788)>: << position startpos moves e2e4 b8c6 g1f3 c6b4 d2d4 g8f6 f3g5 h7h6 c1d2 h6g5 d2b4 e7e6 b4f8 e8f8 f1d3 c7c6 d1d2 f6h5 d2b4 d8e7 b4a5 b7b6 a5a4 h5f4 d3f1 b6b5 a4a5 g5g4 g2g3 f4g6 b1d2 d7d5 e4e5 f7f5 f1g2 a8b8 e1e2 f5f4 a1f1 f4f3 d2f3 g4f3 g2f3 a7a6 f1a1 f8f7 f3g4 e7a7 a5b4 c6c5 d4c5 c8d7 b4d4 b5b4 e2e3 f7e7 h2h4 a6a5 h4h5 g6f8 g4e2 d7c6 d4h4 e7e8 h4d4 a7e7 f2f4 c6a4 b2b3 a4c6 e3f2 e7d8 f2e3 g7g5 h5g6 h8h1 g6g7 h1a1 g7g8q a1a2 e3d2 c6b5 e2b5 b8b5
2024-06-12 11:46:15,814 chess.engine (engine.py:1062) DEBUG <UciProtocol (pid=165788)>: << go wtime 274830 btime 400710 winc 3000 binc 3000
2024-06-12 11:46:16,827 chess.engine (engine.py:1088) DEBUG <UciProtocol (pid=165788)>: >> info depth 3 time 993 nodes 17881
2024-06-12 11:46:16,827 chess.engine (engine.py:1088) DEBUG <UciProtocol (pid=165788)>: >> bestmove f4g5
2024-06-12 11:46:16,828 lib.engine_wrapper (engine_wrapper.py:185) ERROR Ending game due to bot attempting an illegal move.

Didn't do anything to fix it ... the errors just weren't showing up ...
